version: '2'

services:
  app:
    build: .
    image: jumpcloud_connect
    command: amber watch
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/lairan_website_development
    ports:
      - 3000:3000
    links:
      - db
    volumes:
    - .:/app
    - nodes:/app/node_modules
    - shards:/app/lib

  migrate:
    build: .
    image: jumpcloud_connect
    command: bash -c 'amber db migrate seed'
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/lairan_website_development
    volumes:
      - .:/app
    links:
      - db

  danger:
    image: hosteddanger/hosteddanger
    environment: 
      ACCESS_TOKEN: bfc8d6190fa315e4a62506145eda3338bb7a7320
    ports:
      - 80:80
    volumes:
      - ./config.yaml:/opt/hd/config.yaml

  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_ci_development
    volumes:
      - db:/var/lib/postgresql/data


volumes:
  db:
  nodes:
  shards:

